services:
  - type: web
    name: boat-backend
    env: node
    region: frankfurt
    plan: starter
    buildCommand: cd backend && yarn install --frozen-lockfile && yarn build
    startCommand: cd backend && yarn deploy-db && yarn serve
    healthCheckPath: /
    # domains:
    #   - api.clubmaster.io
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: boat-database
          property: connectionString

  - type: web
    name: boat-frontend
    env: static
    buildCommand:
      cd frontend && yarn install --frozen-lockfile && yarn build --configuration production
    staticPublishPath: ./frontend/dist
    # domains:
    #   - clubmaster.io
    envVars:
      - key: angularBackendUrl
        fromService:
          name: boat-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: boat-database
    region: frankfurt
    plan: starter